### ISSUE TITLE
Mods will not load

### ISSUE THREAD

**Issue by RetroactiveTypo** [avivace/ror2-server#29]
Howdy,

Been trying to get this container working with mods, but the mods will not load. Best I can tell when comparing it with a Dedicated Server running on my regular daily driver (Pop! OS), the Preloader loads but the Chainloader never starts. I've ensured the directory is properly set, and the profile works as a dedicated server on my normal machine.

I'm including the log output, but where I see some people's logs include a few references to `Fallback handler could not load library Z:/home/steam/ror2-dedicated/Risk of Rain 2_Data/Mono/data-XXX.dll`, mine is an absolute flood.

I'll include any additional details anyone things are pertinent.

[Server Logs.txt](https://github.com/avivace/ror2-server/files/8057505/logs.txt)

**Comment by willsmi1256** [comment]
I'm getting the same thing here on one of my Debian VMs in ProxMox. This is my first attempt at running this container, but it does work totally fine when I set R2_ENABLE_MODS=0. I put my BepInEx folder, doorstop_config.ini, and winhttp.dll in the mod folder shown in the compose file. 

Logs: [ror2server-2022-02-15T01-40-21.log](https://github.com/avivace/ror2-server/files/8065080/ror2server-2022-02-15T01-40-21.log)
 
Docker Compose: 
```
version: "3"
services:
  ror2server:
    image: avivace/ror2server:latest
    container_name: ror2server
    environment:
      - PUID=1000
      - PGID=1000
      - R2_PLAYERS=6
      - R2_HEARTBEAT=1
      - R2_SV_PORT=27015
      - R2_QUERY_PORT=27016
      - R2_ENABLE_MODS=0
      - R2_HOSTNAME=XXXXXXXXXXXXXX
      - R2_PSW=XXXXXXXXXXXXXXXX
    volumes:
      - /mnt/Files/AppData/Config/ror2server/mods:/home/steam/ror2ds-mods
    ports:
      - 27015:27015/udp
      - 27016:27016/udp
    restart: unless-stopped
```
