### ISSUE TITLE
Whether I set R2_HOSTNAME or not , it only show "??????" in the lobby list.

### ISSUE THREAD

**Issue by bao3** [avivace/ror2-server#46]
The default hostname is "A Risk of Rain 2 dedicated server" , it only show "??????"  too ... what did I miss ?

**Comment by avivace** [comment]
@bao3 did you figure out what was the issue here?

**Comment by bao3** [comment]
> @bao3 did you figure out what was the issue here?

I mean I built the docker container use the docker-compose.yaml:

```
version: "3"
services:
  ror2server:
    image: avivace/ror2server:latest
    container_name: ror2server
    environment:
      - PUID=1000
      - PGID=1000
      - R2_PLAYERS=5
      - R2_HEARTBEAT=1
      - R2_SV_PORT=27018
      - R2_QUERY_PORT=27016
      - R2_ENABLE_MODS=1
      - R2_HOSTNAME="[CN]大宝贝mod"
      - R2_PSW=6
      - R2_GAMEMODE=ClassicRun
    volumes:
      - ./mods:/root/ror2ds-mods
    ports:
      - 27018:27018/udp
      - 27016:27016/udp
      - 27015:27015/udp
    devices:
      - /dev/dri:/dev/dri # For H/W transcoding
         #    logging:
         #driver: none
    restart: unless-stopped

```

I start the container , and it could be shown publicly  in the server list of  Risak of Rain 2 .But the name just "???????"

While I click the "??????" server , in the docker log woule get the error ::

`Warning: wrong connectionId in received user packet`
