### ISSUE TITLE
Server does not see any of arguments.

### ISSUE THREAD

**Issue by KyberJeffHason** [avivace/ror2-server#7]
Hello, I have problem. I am trying to run dedicated server on ubuntu 18.04 with this docker, but server does not see any of arguments I provided.

For example, I run:

docker run -p 25000:27015/udp -e R2_PSW='hello' avivace/ror2server:0.1

25000 port is working, 
but the password was not set for server and I can connect to the server without password.
And I have same problem with R2_PLAYERS and -v $HOST_DIR and maybe other arguments.

And sorry for my english.

**Comment by dubvulture** [comment]
Environment variables seems to be working as I can see them being written in the server configuration file created [here](https://github.com/avivace/ror2-server/blob/20a2c0a6ff02d44138b65f0be007ee88ff08ff1a/entry.sh#L7).
So either that configuration is never actually used, or the game just ignores it.

As of the `-v` volume flag, that's probably another issue, it was suggested [here](https://github.com/avivace/ror2-server/issues/4#issuecomment-674509604) but I'm not sure if it has been tested.

**Comment by jwilling** [comment]
> As of the -v volume flag, that's probably another issue, it was suggested here but I'm not sure if it has been tested.

Yeah I did test it, and it didn't seem to work. I didn't look into it too deeply, so it definitely could have been my fault. Not trying to derail the thread too deeply, but here's the compose file I tried:

```
version "3"
services:
  riskofrain:
    container_name: riskofrain
    image: avivace/ror2server
    ports:
      - "27015:27015/udp"
    volumes:
      - ./data/BepInEx:/home/steam/ror2-dedicated/BepInEx
      - ./data/doorstop_config.ini/:/home/steam/ror2-dedicated/doorstop_config.ini
      - ./data/winhttp.dll:/home/steam/ror2-dedicated/winhttp.dll
```
